---
- name: Destroy
  hosts: undercloud
  gather_facts: false
  vars:
    inventory_generated: "{{ lookup('env', 'TEST_INV_GENERATED') }}"
  tasks:
    - name: Delete tempest directory
      file:
        path: "/tmp/mq_tests_log"
        state: absent

    - block:
        - name: Delete created inventory
          file:
            path: "{{ item }}"
            state: absent
          loop:
            - inventory
            - ansible.ssh.config
            - environments
          delegate_to: localhost

        - name: Restore dump inventory
          copy:
            content: 'localhost ansible_connection=local'
            dest: inventory
          delegate_to: localhost
      when: not inventory_generated
