---
## Network variables
provider_network_type: vlan
provider_physical_network: physnet
provider_segmentation_id: 523

### Subnet variables
allocation_pool_start: 10.10.10.10
allocation_pool_end: 10.10.10.50
cidr: 10.10.10.0/24
dns_nameservers: 10.35.28.28
gateway_ip: 10.10.10.1

##Tasks variables
create_external_network: True
setup_openstack_env: True
create_external_router: True
upload_images: False

#Default images to upload
images:
  - name: cirros
    url: http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
    file: /tmp/cirros-0.3.4-x86_64-disk.img
