---

- name: Set default range
  set_fact: vlan_ids="{{ vlan_id }}:{{ vlan_id }}"

- name: Set Max range if defined
  set_fact: vlan_ids="{{ vlan_id }}:{{ vlan_max_range }}"
  when: "{{ vlan_max_range }} is defined"

- name: Configure physnet2 vlan ids
  replace:
    backup: yes
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    regexp: '^(network_vlan_ranges(?!.*\b{{ vlan_ids }}\b).*)$'
    replace: '\1,physnet2:{{ vlan_ids }}'
  register: network

- name: 'Restart the neutron service'
  service:
    name: neutron-server.service
    state: restarted
  when: network.changed
