---
- name: Switches inventory generation
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    cisco_ip: ''
    junos_ip: ''
  tasks:
    - name: Check for configuration variables
      fail:
        msg: >
          "Variables are not defined.
          Please, define the following variables -
          junos_ip and/or cisco_ip, switch_user, switch_pass, server_name, vlan_id"
      when: not item
      with_items: "{{ junos_ip |default(cisco_ip) }}"

    - name: Add cisco switches to inventory
      add_host:
        name: "{{ item }}"
        groups: "cisco"
        device_type: cisco
        ansible_connection: local
      with_items: "{{ cisco_ip.split(',') }}"
      when: cisco_ip

    - name: Add junos switches to inventory
      add_host:
        name: "{{ item }}"
        groups: "junos"
        device_type: junos
        ansible_connection: local
      with_items: "{{ junos_ip.split(',') }}"
      when: junos_ip

- name: Switches configuration
  hosts: cisco:junos
  connection: local
  gather_facts: no
  roles:
    - configuration/nfv_lab_switches
