---

- name: Check if SRIOV is enabled
  stat:
    path: "/sys/class/net/{{ interface }}/device/sriov_totalvfs"
  register: sriov_status

- name: Fail the play if SRIOV deature is disabled
  fail:
    msg: "SRIOV feaure is disabled on {{ interface }} interface. Please, enable the feature in BIOS and rerun the playbook"
  when: sriov_status.stat.exists == false

- name: Add parameter to the grub
  lineinfile:
    dest: /etc/default/grub
    backrefs: yes
    state: present
    regexp: '^GRUB_CMDLINE_LINUX="(?!.* intel_iommu=on)(.*)"'
    line: 'GRUB_CMDLINE_LINUX="\1 intel_iommu=on"'
  register: grub

- name: Perform - make grub
  command: "grub2-mkconfig -o /boot/grub2/grub.cfg"
  when: grub.changed
  register: makegrub

- name: Set rc.local permissions
  file:
    path: /etc/rc.d/rc.local
    owner: root
    group: root
    mode: "755"

- name: Check the existence of dirver config file
  stat: 
    path: "/etc/modprobe.d/{{ hostvars[inventory_hostname]['ansible_{0}'.format(interface)].module }}.conf"
  register: driver_module

- name: Check the existence of dist.conf file
  stat: 
    path: /etc/modprobe.d/dist.conf
  register: dist

- name: Create a new configuration file
  file: 
    path: "/etc/modprobe.d/{{ item }}"
    state: touch
  with_items:
    - "{{ hostvars[inventory_hostname]['ansible_{0}'.format(interface)].module }}.conf"
    - dist.conf
  when: driver_module.stat.exists == false or dist.stat.exists == false

- name: Set configuration files
  lineinfile:
    dest: "{{ item.file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.context }}"
  with_items:
    - { file: '/etc/rc.local', regexp: '^ip link set {{ interface }} up', context: 'ip link set {{ interface }} up' }
    - { file: '/etc/rc.local', regexp: '^echo 64', context: 'echo 64 > /sys/class/net/{{ interface }}/device/sriov_numvfs' }
    - { file: '/etc/modprobe.d/dist.conf', regexp: '^options vfio_iommu_type1', context: 'options vfio_iommu_type1 allow_unsafe_interrupts=1' }
    - { file: '/etc/modprobe.d/{{ hostvars[inventory_hostname]["ansible_{0}".format(interface)].module }}.conf', regexp: '^options {{ hostvars[inventory_hostname]["ansible_{0}".format(interface)].module }} max_vfs=64', context: 'options {{ hostvars[inventory_hostname]["ansible_{0}".format(interface)].module }} max_vfs=64' }
  register: conffiles

- name: Restart the server
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  when: conffiles.changed or makegrub.changed

- name: Wait for server to restart successfully
  local_action: wait_for host="{{ ansible_default_ipv4.address }}" search_regex=OpenSSH port=22 timeout=300 connect_timeout=30 delay=5

- name: Configure nova conf file
  ini_file:
    dest: "{{ item.file }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{item.value}}"
  with_items:
    - { file: '/etc/nova/nova.conf', section: 'DEFAULT', option: 'pci_passthrough_whitelist',value: '"{"devname": "{{ interface }}", "physical_network":"physnet"}"' }
  notify: 'Restart nova compute service'
