---

- name: "Keypair {{ resource_state }}"
  vars:
    ansible_python_interpreter: "{{ venv_path }}/bin/python"
  os_keypair:
    cloud: "{{ item.cloud_name | default(cloud_name) }}"
    state: "{{ resource_state }}"
    name: "{{ item.name }}"
    validate_certs: "{{ validate_certs | default(omit) }}"
  loop: "{{ keypairs }}"
  register: reg_keypair

- name: Create private key for vm connection
  copy:
    content: "{{ item.key.private_key }}"
    dest: "{{ resources_output_file | dirname }}/{{ item.item.name }}.key"
    mode: 0600
  loop: "{{ reg_keypair.results }}"
  no_log: true
  when: item.changed and item.id is defined

- name: Fetch private key from generated keypair
  fetch:
    src: "{{ resources_output_file | dirname }}/{{ item.item.name }}.key"
    dest: "/tmp/{{ item.item.name }}.key"
    flat: yes
  loop: "{{ reg_keypair.results }}"
  no_log: true
  when: item.changed and item.id is defined
