---

- name: Add quota to project
  vars:
    ansible_python_interpreter: "{{ venv_path }}/bin/python"
  os_quota:
    cloud: "{{ item.0.cloud_name | default(cloud_name) }}"
    name: "{{ item.0.project }}"
    cores: "{{ item.1.cores | default(omit) }}"
    ram: "{{ item.1.ram | default(omit) }}"
    instances: "{{ item.1.instances | default(omit) }}"
    volumes: "{{ item.1.volumes | default(omit) }}"
    floating_ips: "{{ item.1.floating_ips | default(omit) }}"
    fixed_ips: "{{ item.1.fixed_ips | default(omit) }}"
    state: "{{ resource_state }}"
    validate_certs: "{{ validate_certs | default(omit) }}"
  loop: "{{ users | subelements('quota', 'skip_missing=True') }}"
  when: resource_state == 'present'
