---

- name: "Security groups {{ resource_state }}"
  vars:
    ansible_python_interpreter: "{{ venv_path }}/bin/python"
  os_security_group:
    cloud: "{{ item.cloud_name | default(cloud_name) }}"
    name: "{{ item.name }}"
    state: "{{ resource_state }}"
  loop: "{{ security_groups }}"
  register: reg_secgroup

- name: Add ICMP and SSH protocols
  vars:
    ansible_python_interpreter: "{{ venv_path }}/bin/python"
  os_security_group_rule:
    cloud: "{{ item.0.cloud_name | default(cloud_name) }}"
    security_group: "{{ item.0.name }}"
    protocol: "{{ item.1.protocol }}"
    port_range_min: "{{ item.1.port_range_min }}"
    port_range_max: "{{ item.1.port_range_max }}"
    remote_ip_prefix: "{{ item.1.remote_ip_prefix }}"
  loop: "{{ security_groups | subelements('rules', 'skip_missing=True') }}"
  when: reg_secgroup.results.0.id is defined
