---
### Task execution variables
setup_openstack_env: True
routers_and_networks: True
upload_images: False
port_security: False

### Networks
### Define the networks that should be created on the overcloud,
### 'External: true' value could be defined just for the external network.
### Allocation pools could be defined as an option in case specific pool range should be defined.
### Otherwise, pool will be calculated by 'cidr' value.
networks:
  - name: public
    physical_network: public
    segmentation_id: 25
    external: true
    allocation_pool_start: 10.0.0.12
    allocation_pool_end: 10.0.0.100
    cidr: 10.0.0.0/24
    enable_dhcp: false
    gateway_ip: 10.0.0.254
    router_name: router1
  - name: private
    physical_network: tenant
    segmentation_id: 32
    cidr: 172.20.0.0/24
    enable_dhcp: true
    gateway_ip: 172.10.0.254
    router_name: router1

network_type: vlan
dns_nameservers:
  - 8.8.8.8
  - 8.8.4.4

#Default images to upload
images:
  - name: cirros
    url: http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
