---
- name: Set login banner
  ios_banner:
    provider: "{{ credentials }}"
    banner: motd
    text: |
      NFV QE Juniper switch

      The switch is under NFV QE team management.
      Do not change configuration as it will be overriden by the playbook.

      Contact info - nfv-cloud-qe-team[at]redhat.com
    state: present

# Once moving to ansible 2.5 version, use this task instead of the next three.
# Version 2.5 still has some bugs that prevents us to use it.
# - name: Create required VLAN
#   ios_vlan:
#     provider: "{{ credentials }}"
#     name: "vlan{{ vlan_id }}"
#     vlan_id: "{{ vlan_id }}"
#     state: present
#
# - name: Set requested Interfaces to access and attach to a vlan
#   ios_l2_interface:
#     provider: "{{ credentials }}"
#     name: "{{ item }}"
#     mode: access
#     access_vlan: "{{ vlan_id }}"
#     state: present
#   with_items: "{{ vars[server_name_item].ports }}"

- name: Set description on requested Interfaces
  ios_config:
    provider: "{{ credentials }}"
    lines:
      - "description {{ server_name_item }}"
    parents: "interface {{ item }}"
  with_items: "{{ vars[server_name_item].ports }}"

- name: Set access VLAN ID to requested Interfaces
  ios_config:
    provider: "{{ credentials }}"
    lines:
      - "switchport access vlan {{ vlan_id }}"
    parents: "interface {{ item }}"
  with_items: "{{ vars[server_name_item].ports }}"

- name: Save configuration
  ios_config:
    provider: "{{ credentials }}"
    save_when: modified
