# Parse trex configuration during run time from trex instance
gather_trex_conf_live: True

# Destination of trex config file
trex_conf_file: '/etc/trex_cfg.yaml'

# Clone trafficgen repo https://github.com/atheurer/trafficgen
clone_traffic_gen_repo: True

# Trafficgen repo URI
trafficgen_repo: 'https://github.com/atheurer/trafficgen'

# Trafficgen branch
trafficgen_branch: 'master'

# Derecitory where trafficgen repo will be cloned to
trafficgen_dir: '/opt/trafficgen/'

# Platform sepcific Trex configuration
trex_platform:
  master_thread_id: 0
  latency_thread_id: 1
  dual_if:
    - socket: 0
      threads: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

# DPDK root dir
dpdk_root_dir: '/root/dpdk'

# Workaround - can't define this variable inside playbook
trex_full_nic_info: []
