# DPDK directory on host
dpdk_root_dir: '/root/dpdk'

# Compiled DPDK binaries directory
dpdk_compiled_dir: '{{ dpdk_root_dir }}/build/app'

hugepages_count: 64

# Use Mellanox drivers
use_mellanox_drivers: False
