---
## Openstack variables
tripleo_overcloud_file: /home/stack/overcloudrc
tripleo_undercloud_file: /home/stack/stackrc

clouds_yaml_file_path: ~/.config/openstack/clouds.yaml

packages:
  rhel8:
    - gcc
    - libffi-devel
    - platform-python-devel
    - platform-python-setuptools
    - git
  rhel7:
    - gcc
    - libffi-devel
    - python-devel
    - python-setuptools
