# binary-search script result log file to be generated on undercloud
binary_perf_log: '/tmp/performance.log'

# Trafficgen repo directory on host
trafficgen_dir: '/opt/trafficgen'

# binary-search binary
binary_search_bin: "{{ trafficgen_dir }}/binary-search.py"

# Frame size in bytes that Trex will generate
trex_frame_size: 64

# Max packet lost % acceptable
trex_max_lost_pct: 0.00

# Number of unique flows
trex_flows: 1

# Minimum rate for of packets to generate, sized in mpps(milion packets per second)
trex_rate: 2

# Enables using vlan-ids with binary-search
trex_set_vlan: False
