---

### variables
tempest_dir: /mnt
image_ssh_user: cloud-user

### Static variables
tempest_url: https://github.com/redhat-openstack/tempest 
plugin_url: https://review.gerrithub.io/redhat-openstack/tempest-nfv-plugin

### Openstack variables
osp_image: http://file.tlv.redhat.com/~itbrown/images/rhel-guest-image-7.2-20151102.0.x86_64.qcow2
keystone: /root/keystonerc_admin

## Port_vnic_type direct
port_vnic_type: False
