#- name: Fetch image from URL
#  get_url:
#    url: "{{ guest_image | mandatory }}"
#    dest: "{{ guest_image_output }}"
#    mode: 0640
#    validate_certs: False
#  register: image_result

- name: Set path of fetched image
  set_fact:
#    fetched_image: "{{ image_result['dest'] }}"
    fetched_image: "/tmp/CentOS-8-GenericCloud-8.3.2011-20201204.2.x86_64.qcow2"
