---

# Virtual environment path
venv_path: "/tmp/ansible_venv"

# Undercloud host name/ip
# host:

# Undercloud user. Default - stack
# user:

# Define one of the following.
# In case ssh_pass is used, dynamic ssh key will be generated and used.
# ssh_key:
# ssh_pass:

# Define the type of the environment.
# Could be - baremetal, virt.
# For baremetal environment add ```-e setup_type=baremetal```
# and for virt or hybrid environment add ```-e setup_type=virt```
setup_type: baremetal

overcloud_user: heat-admin
