---

# Define the type of the environment.
# Could be - baremetal, virt.
# For baremetal environment use - baremetal
# and for virt or hybrid environment use - virt
setup_type: baremetal

# Undercloud host name/ip
# host:

# Undercloud user. Default - stack
# user:

# Define one of the following.
# In case ssh_pass is used, dynamic ssh key will be generated and used.
# ssh_key:
# ssh_pass:

overcloud_user: heat-admin

# Define custom undercloud user if required.
# By default the variable is not used.
# Default value is - stack.
# custom_undercloud_user:

# Virtual environment path
venv_path: "/tmp/ansible_venv"

# Define the groups, Undercloud host should be added to.
# multiple groups should be separated by the comma.
undercloud_groups: undercloud,tester
