---

- name: Create network
  vars:
    ansible_python_interpreter: "/root/.venv/bin/python"
  os_network:
    cloud: openstack
    name: "{{ external_network_name }}"
    state: present
    external: true
    provider_network_type: "{{ provider_network_type }}"
    provider_physical_network: "{{ provider_physical_network }}"
    provider_segmentation_id: "{{ provider_segmentation_id }}"
  register: openstack_networks

- name: Create subnet
  vars:
    ansible_python_interpreter: "/root/.venv/bin/python"
  os_subnet:
    cloud: openstack
    name: external_subnet
    allocation_pool_start: "{{ allocation_pool_start }}"
    allocation_pool_end: "{{ allocation_pool_end }}"
    cidr: "{{ cidr }}"
    dns_nameservers: "{{ dns_nameservers }}"
    enable_dhcp: False
    network_name: "{{ external_network_name }}"
    gateway_ip: "{{ gateway_ip }}"
    state: present
