# testpmd binary
testpmd_bin: "{{ dpdk_compiled_dir }}/dpdk-testpmd"

# Map list of cores to physical cpu set
testpmd_lcores: '3,4,7'

# Mumber of memory channels to use
testpmd_mem_channels: 4

# Memory to allocate per socket
testpmd_socket_mem: 1024

# Number of cores to execute testpmd on
testpmd_forward_cores: 2

# TestPMD TX Queue size
testpmd_rxd: 1024

# TestPMD RX Queue size
testpmd_txd: 1024

# Number of TestPMD TX Queues
testpmd_rxq: 1

# Number of TestPMD RX Queues
testpmd_txq: 1

# TestPMD forwarding mode
forward_mode: io
