---

### Run triggers
setup_os_env: true
create_networks: true
create_flavors: true
images_upload: true
overcloud_delete: false
boot_instance: false

### Networks
### Define the networks that should be created on the overcloud.
### 'External: true' value could be defined just for the external network.
### Allocation pools could be defined as an option in case specific pool range should be defined.
### Otherwise, pool will be calculated by 'cidr' value.
### 'network_type' and 'ip_version' arguments could be defined as an option.
### By default, 'network_type' uses 'vlan', 'ip_version' uses 'ipv4'
### 'gateway_ip' could be defined in case there is a need to specify gateway ip address.
networks:
  - name: public
    physical_network: public
    segmentation_id: 25
    network_type: vlan
    external: true
    allocation_pool_start: 10.0.0.12
    allocation_pool_end: 10.0.0.100
    cidr: 10.0.0.0/24
    enable_dhcp: false
    gateway_ip: 10.0.0.254
    router_name: router1
    ip_version: 4
  - name: private
    physical_network: tenant
    segmentation_id: 32
    cidr: 172.20.0.0/24
    router_name: router1

dns_nameservers:
  - 8.8.8.8
  - 8.8.4.4

#Default images to upload
images:
  - name: cirros
    url: http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img

# Default flavor to create
flavors:
  - name: nfv-flavor
    ram: 4096
    disk: 20
    vcpus: 4
    property:
      - "hw:mem_page_size=1GB"
      - "hw:numa_mempolicy=preferred"
      - "hw:numa_mem.0=4096"
      - "hw:numa_nodes=1"
      - "hw:numa_cpus.0=0,1,2,3"
      - "hw:cpu_policy=dedicated"

instance_name: vm1
group_name: tested_vms
