---
- name: Prepare
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    env_host: "{{ lookup('env', 'TEST_HOST') }}"
    env_ssh_key: "{{ lookup('env', 'TEST_SSH_KEY') }}"
    env_type_override: "{{ lookup('env', 'TEST_ENV_TYPE') }}"
    env_type: "{{ (env_type_override | length > 0) | ternary(env_type_override, 'virt') }}"
    inventory_generated: "{{ lookup('env', 'TEST_INV_GENERATED') }}"
  roles:
    - role: post_install/tripleo_inventory
      host: "{{ env_host }}"
      ssh_key: "{{ env_ssh_key }}"
      setup_type: "{{ env_type }}"
      inv_path: "{{ lookup('env', 'PWD') }}/molecule/default"
      when: not inventory_generated
